### ISSUE TITLE
`DATA` names follow wrong convention

### ISSUE THREAD

**Issue by coretl** [PandABlocks/PandABlocks-ioc#101]
At the moment names for the `DATA` block are `FieldName` while everything else is `FIELD_NAME`. This means that the pvi name (as calculated by `epics_to_pvi_name()`) is `fieldname` where it should be `field_name`.

E.g.:
https://github.com/PandABlocks/PandABlocks-ioc/blob/acfefb3da61db47a32d6fff71f26236c35909812/src/pandablocks_ioc/_hdf_ioc.py#L442

should be `:FLUSH_PERIOD`.

**Comment by evalott100** [comment]
This shouldn't be a breaking change for users who have been using the pascal case alias for in their code. It will be for anyone who was using the upper case PVs ... however those are incorrectly formatted anyway.
