### ISSUE TITLE
DATASETS table PV empty despite positions set to be captured

### ISSUE THREAD

**Issue by jwlodek** [PandABlocks/PandABlocks-ioc#129]
It is possible that I am missing something in the IOC setup for the datasets, but I am running into an issue where the `DATASETS` table that ophyd-async is using for generating resource/datum docs for each dataset is empty, despite there being positions set to capture on the panda.

Running a scan w/ the panda through bluesky does correctly save the HDF file, with the typical position names as the dataset path, but no resource/datum docs are generated due to the empty table, so the data is inaccessible from databroker/tiled. Below is `pvget` on some of the PVs of interest.

```
[jwlodek@xf27id1-ws1 ~]$ pvget XF:27ID1-ES{PANDA:1}:DATA:DATASETS
XF:27ID1-ES{PANDA:1}:DATA:DATASETS 
Name Type
[jwlodek@xf27id1-ws1 ~]$ pvget XF:27ID1-ES{PANDA:1}:PCAP:TS_START:CAPTURE
XF:27ID1-ES{PANDA:1}:PCAP:TS_START:CAPTURE 2024-08-28 17:02:43.202  (1) Value
[jwlodek@xf27id1-ws1 ~]$ pvget XF:27ID1-ES{PANDA:1}:PCAP:TS_START:DATASET
Timeout
```

I will try to debug when I have some free time.

**Comment by jwlodek** [comment]
After some looking at the source code/testing, I was able to figure out what was happening - the `DATASETS` table is only updated when the HDF5 capture is started, based on the values in the `DATASET` PVs for each position. I wonder if it would be good to also update the table whenever a `CAPTURE` or `DATASET` PV is written to, so that the table can be checked without having to open an HDF file

**Comment by evalott100** [comment]
> so that the table can be checked without having to open an HDF file
I remember intitially doing this but we had some reason to restrict it to updating once write starts @coretl

**Comment by coretl** [comment]
> After some looking at the source code/testing, I was able to figure out what was happening - the `DATASETS` table is only updated when the HDF5 capture is started, based on the values in the `DATASET` PVs for each position. I wonder if it would be good to also update the table whenever a `CAPTURE` or `DATASET` PV is written to, so that the table can be checked without having to open an HDF file

Ah, I remember this now. The issue is that we should be reporting `DATASETS` whenever the HDF capture is started because that is the point where the datasets are created and written to. Writing to the `DATASET` PVs during a scan has no effect until the next scan.

Does this ordering work?
- Set the `DATASET` PVs
- Start HDF capture
- Read `DATASETS` table

Is this what ophyd-async is doing?

**Comment by jwlodek** [comment]
Ok, yes that makes sense to me. I will try this out today.

What might be valuable is to have a check on `writer.open` in `ophyd-async` to see if the table is empty and printing a warning of some kind that lets the user know to check the `:DATASET` PVs. Thoughts?

If that's something worthwhile I can make a PR.

**Comment by coretl** [comment]
> Ok, yes that makes sense to me. I will try this out today.
> 
> What might be valuable is to have a check on `writer.open` in `ophyd-async` to see if the table is empty and printing a warning of some kind that lets the user know to check the `:DATASET` PVs. Thoughts?
> 
> If that's something worthwhile I can make a PR.

That sounds good, yes please
