### ISSUE TITLE
Phoebus screen for positions appears to make everything integers, rather than floats.

### ISSUE THREAD

**Issue by jwlodek** [PandABlocks/PandABlocks-ioc#134]
![image](https://github.com/user-attachments/assets/f1d56ad0-7003-4521-8e94-3a5d0a1f0593)

I will double check if this is the case on the most recent screen auto-generation, but at the moment the screens appear to be configured to display as ints which makes setting scaling difficult.

**Comment by evalott100** [comment]
I've just pulled off main and `units` PVs seem to erroneously be duplicates of the `value` field too... Different problem...

Can you screenshot your INENC screen too? It seems that the widget is set up with a precision of `-1` - which I would assume means to get the precision from the PV, however it seems we've left this undefined on the `NTScalar`.

**Comment by coretl** [comment]
@evalott100 not sure what `PREC` is when you make the `ai` record in builder, but 5 would be a reasonable number for it

**Comment by evalott100** [comment]
> @evalott100 not sure what `PREC` is when you make the `ai` record in builder, but 5 would be a reasonable number for it

This is a calc record

https://github.com/PandABlocks/PandABlocks-ioc/blob/c4dea928950fdab47c7843d4f0a51ac84c999eba/src/pandablocks_ioc/ioc.py#L919-L926

But calc records default to `PREC=0`. I've changed it to 5 and (fixed the units column).

![image](https://github.com/user-attachments/assets/79cbf5ed-4c9b-4fac-82e0-b2b781f37329)
