### ISSUE TITLE
Support DeviceVectors in pvi structures

### ISSUE THREAD

**Issue by coretl** [PandABlocks/PandABlocks-ioc#138]
To support https://github.com/bluesky/ophyd-async/issues/624

We need to keep back compat of the `.pvi` field, but are free to change the `.value` field as no-one is using it yet.

I propose we change the device level PVI to look like:
```
    info(Q:group, {
        "$(P):PVI": {
            # New usage gets DeviceVectors
            "value.pulse[1].d": {
                "+channel": "VAL",
                "+type": "plain"
            },
            # Back compat gets flat structure
            "pvi.pulse1.d": {
                "+channel": "VAL",
                "+type": "plain"
            }
        }
    })
```

**Comment by evalott100** [comment]
Happy to carry this over (in the same backwards compatible way) to fastcs.
