### ISSUE TITLE
Artifacts in PV names

### ISSUE THREAD

**Issue by dmgav** [PandABlocks/PandABlocks-ioc#32]
Panda app may contain one or more blocks of the same type. If a single instance of a block is loaded in Panda (PCAP, BITS), the block name does not end with the block number. Names for the blocks with multiple instances end with the block number (one or more digits, such as COUNTER1, COUNTER2 etc.). This naming convention propagates to PVs, for example

```
PANDA:PCAP:ENABLE
PANDA:COUNTER1:ENABLE
```

The PV names are further used to generate attributes of the Panda Ophyd object: separate blocks (names not ending with numbers) are represented as separate attributes and groups of object instances (names ending with numbers) are represented as attributes pointing to device arrays.

**The Issue with Naming**

The names have the following inconsistency: if a single instance of a block is loaded into Panda, all block parameters are accessible using the block name with no number in it except `LABEL`, which is downloaded from Panda as part of metadata.
This inconsistency is propagated to PV names:

```
PANDA:PCAP:ENABLE
PANDA:PCAP1:LABEL
```

Since PV names are distributed via PVI and used to dynamically generate Ophyd object attributes, the inconsistency breaks the logic in the Ophyd object. Temporary fix, which simply ignores the 'numbered' object if 'non-numbered' object exists was implemented in PR https://github.com/bluesky/ophyd-epics-devices/pull/39

**Source of the Problem**

The values for `LABEL` attribute are loaded as part of metadata and the attribute names are handled separately from other names. Initially, the attribute names are listed in the file `/share/panda-fpga/config_d` distributed as part of `panda-fpga` .ZPG archive. The metadata attributes are listed separately for other attributes of objects and all names of existing blocks end with a block number (see names for PCAP, BITS etc.):

```
*METADATA
    APPNAME             constant =PandABox-no-fmc
    DESIGN              string
    LAYOUT              multiline
    EXPORTS             multiline
    LABEL_TTLIN1        string
    LABEL_TTLIN2        string
    LABEL_TTLIN3        string
    LABEL_TTLIN4        string
    LABEL_TTLIN5        string
    LABEL_TTLIN6        string
    LABEL_TTLOUT1       string
    LABEL_TTLOUT2       string
    LABEL_TTLOUT3       string
    ...
    LABEL_PCAP1         string
    LABEL_SYSTEM1       string
    LABEL_BITS1         string
```

The Panda server is using this file to populate the table of parameters, which in turn is used to generate the dictionary of changes, which is loaded by the IOC:
https://github.com/PandABlocks/PandABlocks-ioc/blob/9c6495ea39f93a1874524fd94020c53a56014909/src/pandablocks_ioc/ioc.py#L252
The keys of the dictionary are then used to create the PV names. 

**Possible Fix**

It is not clear on which level in the stack the issue has to be fixed. For example, the naming in`/share/panda-fpga/config_d` config file does not look inconsistent: all names in the `*METADATA` section contain numbers and each type of blocks is listed under its own sections with section name consisting of the block name followed by the number of block instances.

One possible solution is to modify the downloaded `changes` dictionary by removing numbers from metadata names for single blocks. This could be achieved by putting the following or similar code after https://github.com/PandABlocks/PandABlocks-ioc/blob/9c6495ea39f93a1874524fd94020c53a56014909/src/pandablocks_ioc/ioc.py#L257

```
    import re

    base_keys = set([_.split(".")[0] for _ in changes.values.keys()])
    values_fixed = dict()
    for k, v in changes.values.items():
        k_fixed = k
        if k.startswith("*METADATA.LABEL_"):
            suffix = re.sub(r"^\*METADATA\.LABEL_", "", k)
            suffix_no_num = re.sub(r"\d$", "", suffix)
            if suffix_no_num in base_keys:
                k_fixed = re.sub(r"\d$", "", k)
        values_fixed[k_fixed] = v

    changes.values = values_fixed
```

which seems to fix the problem (at the first glance):

```
$ caget -S PANDA:BITS:LABEL
PANDA:BITS:LABEL Soft inputs and constant bits
$ caget -S PANDA:PCAP:LABEL
PANDA:PCAP:LABEL Position capture control
$ caget PANDA:PCAP:ENABLE
PANDA:PCAP:ENABLE              ONE
```

**Comment by AlexanderWells-diamond** [comment]
I believe there are changes in this area, possibly exactly the changes outlined here, currently waiting in PR #29 - and the original discussion for it was in PR #26.

**Comment by dmgav** [comment]
The issue is resolved in https://github.com/PandABlocks/PandABlocks-ioc/pull/30.
