### ISSUE TITLE
New PVI group for counters

### ISSUE THREAD

**Issue by evalott100** [PandABlocks/PandABlocks-ioc#57]
Move the fields from here

![image](https://github.com/PandABlocks/PandABlocks-ioc/assets/21142790/ebfd2f42-4c9f-466a-8381-59deb9e42f46)

into a new group on counters, and also add a button that displays the counter in the Positions table

**Comment by coretl** [comment]
To be clear, this is not just about counters, but all `pos_out` fields. The capture, offset, scale and units should be moved to a new `Capture` group.
