### ISSUE TITLE
Delete scalar indices from seq tables

### ISSUE THREAD

**Issue by coretl** [PandABlocks/PandABlocks-ioc#70]
For PandA tables, we store them in waveform records, with one for each column, We also have an `index` record, and a scalar record per column that allows you to see a single row of the table. This was conceived before Phoebus had PVA NTTable support, and never worked properly. In fact it makes it fail if you have an empty table. I propose we delete the index and scalar records from tables.

@dmgav you aren't using this feature are you?

**Comment by dmgav** [comment]
No, I don't think we do if I understand the issue correctly.
