### ISSUE TITLE
Change hdf writing PVs

### ISSUE THREAD

**Issue by evalott100** [PandABlocks/PandABlocks-ioc#80]
The following was discussed in person with @coretl  @jsouter and myself.

I'd be interested to hear your opinions @AlexanderWells-diamond 

Currently we have:
* Flush options for PCAP, added in #73 
   * Confusingly these options are for the PCAP, but are currently in HDF5.
   * We'll scrap the `FlushMode` altogether and make `flush_period == 0` control immediate  flushing
* In #78 we add more PVs to control HDF flushing
  * These should be changed to `DATA:HDFDirectory` `DATA:HDFFileName` and `DATA:HDFFullFilePath`. Likewise, the other PVs should be changed to the below diagram.

This new architecture will look like:
 

![Untitled-2023-11-28-1041](https://github.com/PandABlocks/PandABlocks-ioc/assets/21142790/e5f7dd06-9e3c-4d0e-86cd-4cb79b8a70ea)

# Updates

* The releases of pandablock-ioc and pandablocks-client are now changed:
    * https://github.com/PandABlocks/PandABlocks-client/releases/tag/0.6.1 is the most recent release of pandablock-client
    * https://github.com/PandABlocks/PandABlocks-ioc/releases/tag/0.3.2 is the most recent release of pandablocks-ioc
    * Both lack the `add_manual_flush` commits which are in the `add_manual_flush` branch on each repo

**Comment by coretl** [comment]
Some suggestions:

```
|Capture|
DATA:CaptureMode
DATA:NumCapture
DATA:NumCaptured
DATA:Capture
DATA:Capturing
DATA:FlushPeriod

|HDF|
DATA:HDFDirectory
DATA:HDFFileName
DATA:HDFFullFilePath
DATA:HDFStatus
```

**Comment by coretl** [comment]
@dmgav we will implement the `Last N` mode to provide the same functionality as https://github.com/dmgav/PandABlocks-ioc-ringbuf/blob/ea6a3b5cd82172747776d89df8c6e7d7edcca9a0/pandablocks_ioc_ringbuf/_hdf_ioc.py#L244-L377
