### ISSUE TITLE
IOC does not properly function when recorded data includes mean value

### ISSUE THREAD

**Issue by dmgav** [PandABlocks/PandABlocks-ioc#93]
Note: This issue may caused by the upstream software/firmware layer. The IOC may function as expected. I included this issue here because it was found while testing the IOC.

The issue is observed if the option to record `mean` value is selected for at least one of the positions:
![image](https://github.com/PandABlocks/PandABlocks-ioc/assets/46980826/c29fdedf-f39c-4c2f-8fce-a7b512728475)

Also let's assume that `Gate Duration Caputure` is disabled in PCAP settings:
![image](https://github.com/PandABlocks/PandABlocks-ioc/assets/46980826/9e3164ef-3a83-4289-8e32-3d58758cdb7f)

Attempting to record data to HDF5 file results in the following error displayed in the IOC output:
```
Exception in thread Thread-22:
Traceback (most recent call last):
  File "/nsls2/users/dgavrilov/.conda/envs/panda-ioc/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/nsls2/users/dgavrilov/repos/PandABlocks-client/src/pandablocks/hdf.py", line 64, in run
    data = func(data)
           ^^^^^^^^^^
  File "/nsls2/users/dgavrilov/repos/PandABlocks-client/src/pandablocks/hdf.py", line 178, in scale_data
    return [process(data.data) for process in self.processors]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nsls2/users/dgavrilov/repos/PandABlocks-client/src/pandablocks/hdf.py", line 178, in <listcomp>
    return [process(data.data) for process in self.processors]
            ^^^^^^^^^^^^^^^^^^
  File "/nsls2/users/dgavrilov/repos/PandABlocks-client/src/pandablocks/hdf.py", line 164, in <lambda>
    lambda data: data[column_name] * field.scale / data[SAMPLES_FIELD]
                                                   ~~~~^^^^^^^^^^^^^^^
ValueError: no field of name PCAP.SAMPLES.Value
```

By adding debug prints to the IOC code it was found that `dtype=[('PCAP.GATE_DURATION.Value', '<i4'),` is still included in the collected data, despite being disabled in the PCAP settings. The possible reason for the observed issue is that  **`PCAP.GATE_DURATION.Value` is being collected instead of the expected `PCAP.SAMPLES.Value`**.

If `Gate Duration Capture` is enabled in PCAP settings and the `mean` option is selected for one of the positions, then the IOC fails with 
```
ERROR:HDF5 data capture terminated due to unexpected error
Traceback (most recent call last):
  File "/nsls2/users/dgavrilov/repos/PandABlocks-ioc/src/pandablocks_ioc/_hdf_ioc.py", line 553, in _handle_hdf5_data
    async for data in self._client.data(
  File "/nsls2/users/dgavrilov/repos/PandABlocks-client/src/pandablocks/asyncio.py", line 179, in data
    for data in await queue.get():
  File "/nsls2/users/dgavrilov/repos/PandABlocks-client/src/pandablocks/connections.py", line 394, in receive_bytes
    yield from ret
  File "/nsls2/users/dgavrilov/repos/PandABlocks-client/src/pandablocks/connections.py", line 325, in _handle_header_body
    self._frame_dtype = np.dtype(
                        ^^^^^^^^^
ValueError: field 'PCAP.GATE_DURATION.Value' occurs more than once
```
probably because `PCAP.GATE_DURATION.Value` is added twice to the output stream. 

As as side note, if `Gate Duration Capture` is disabled and there are no positions with `mean` option selected, then `PCAP.GATE_DURATION.Value` is not in the data stream (as expected).

**Comment by evalott100** [comment]
I'll start working on this.

We think it's because the name change from `PCAP.SAMPLES` to `PCAP.DURATION` in the firmware has not been taken account of in Pandablocks-client.

**Comment by dmgav** [comment]
Yes, it looks like it is expected that `PCAP.SAMPLES.Value` is added to the data stream automatically whenever one of the collected positions has `mean` option selected, but `PCAP.GATE_DURATION.Value` is added to the stream instead. And if `Gate Duration Capture` is enabled, then `PCAP.GATE_DURATION.Value` is added to the stream twice (this is a separate mode of failure). I did not trace where this happens. `PCAP.SAMPLES.Value` is used here:
https://github.com/PandABlocks/PandABlocks-client/blob/0385fd5e91d0823a4117a8b2ab52f9eaa9258469/src/pandablocks/hdf.py#L162-L166

**Comment by evalott100** [comment]
> Yes, it looks like it is expected that `PCAP.SAMPLES.Value` is added to the data stream automatically whenever one of the collected positions has `mean` option selected, but `PCAP.GATE_DURATION.Value` is added to the stream instead. And if `Gate Duration Capture` is enabled, then `PCAP.GATE_DURATION.Value` is added to the stream twice (this is a separate mode of failure). I did not trace where the bug is. `PCAP.SAMPLES.Value` is used here: https://github.com/PandABlocks/PandABlocks-client/blob/0385fd5e91d0823a4117a8b2ab52f9eaa9258469/src/pandablocks/hdf.py#L162-L166

Here we are: https://github.com/PandABlocks/PandABlocks-FPGA/pull/155
I'll adjust the client to work with either `SAMPLES` or `GATE_DURATION`. 

The repeated `PCAP.GATE_DURATION.Value` seems strange? @coretl

**Comment by evalott100** [comment]
Yup, with these settings
![image](https://github.com/PandABlocks/PandABlocks-ioc/assets/21142790/0543dd45-376b-4f09-80cf-32920a5799fc)
we get two `GATE_DURATION` values

```
[twj43146@pc0139 PandABlocks-ioc-fork]$ nc <ip> 8889
RAW
OK
arm_time: 2024-02-23T13:12:13.244843663Z
start_time: 2024-02-23T13:12:13.244893217Z
missed: 0
process: Raw
format: ASCII
fields:
 PCAP.GATE_DURATION int32 Value scale: 8e-09 offset: 0 units: s
 PCAP.GATE_DURATION int32 Value scale: 8e-09 offset: 0 units: s
 COUNTER1.OUT int32 Min scale: 1 offset: 0 units: 
 COUNTER1.OUT int32 Max scale: 1 offset: 0 units: 
 PCAP.TS_TRIG int64 Value scale: 8e-09 offset: 0 units: s
 COUNTER1.OUT int64 Mean scale: 1 offset: 0 units: 

 0x02ab6d92 0x02ab6d92 0x00026c88 0x00026c88 0x02ab6d92 0x00000000 0x986fcd90 0x00000678
 0x07735940 0x07735940 0x00026c88 0x00026c89 0x0a1ec6d2 0x00000000 0x58e1c33f 0x0000120f
 ...
```

Strange though, I'm trying to set it up to do this again now (5 minutes later) and it's working as expected..
```
arm_time: 2024-02-23T13:17:55.024877962Z
start_time: 2024-02-23T13:17:55.024925986Z
missed: 0
process: Scaled
format: ASCII
fields:
 PCAP.GATE_DURATION double Value scale: 8e-09 offset: 0 units: s
 COUNTER1.OUT double Min scale: 1 offset: 0 units: 
 COUNTER1.OUT double Max scale: 1 offset: 0 units: 
 PCAP.TS_TRIG double Value scale: 8e-09 offset: 0 units: s
 COUNTER1.OUT double Mean scale: 1 offset: 0 units: 
```

There must be something strange going on... I'll try to reproduce once more.

**Comment by coretl** [comment]
yeah, RAW mode will be different to SCALED (the default). Please can you make an issue in PandABlocks-server when you have a reproducer?

**Comment by evalott100** [comment]
Okay, I can reproduce. It produces two when it's in RAW mode and one when it's in scaled. That's the only difference.
